// ─── רישום השדות של טופס 1301 — מקור האמת ──────────────────────────────────
//
// כל שדה מצהיר על:
//   - fieldNumber: מזהה פנימי ייחודי. כשיש התאמה 1:1 לקוד רשמי — זה הקוד עצמו.
//   - codes: הקודים הרשמיים לפי בעלות (רשום/בן זוג/משותף) — מקור האמת מול הטופס.
//   - dataLayer: מודל שלוש השכבות — question / document / accountant / auto.
//   - officialRef: עמוד במדריך רשות המיסים 2025 שמאמת את המיפוי.
//   - מתי הוא חי (always / conditional), modelPath, sourceQuestionIds, מסמכים.
//
// אימות: כל קוד רשמי כאן הוצלב מול "מדריך רשות המיסים למילוי דוח שנתי ליחיד
// (טופס 1301) לשנת 2025" — ראה docs/1301_coverage_gap_2025.md לביקורת המלאה.
// השינויים בטופס 1301 ו/או בעץ ההחלטות מתחילים תמיד מהקובץ הזה.

import type { Form1301FieldDef, TaxpayerModel } from './types';

// כל ה-helpers מוגנים נגד מודל חלקי (שמגיע מסשנים ישנים שלא עברו עוד מיגרציה).
const has = (m: TaxpayerModel, kind: string) =>
  (m.income?.sources ?? []).includes(kind as TaxpayerModel['income']['sources'][number]);

const isMarried = (m: TaxpayerModel) => m.identity?.maritalStatus === 'married';

const anyNiBenefit = (m: TaxpayerModel) =>
  m.income?.niMaternityReceived === true ||
  m.income?.niUnemploymentReceived === true ||
  m.income?.niReserveDutyReceived === true ||
  m.income?.niWorkInjuryReceived === true;

/** בחר סוג הפסד ברשימת ההפסדים החדשה. */
const hasLoss = (m: TaxpayerModel, kind: NonNullable<TaxpayerModel['losses']['kinds']>[number]) =>
  (m.losses?.kinds ?? []).includes(kind);

// ─── הרישום ─────────────────────────────────────────────────────────────

export const form1301Fields: Form1301FieldDef[] = [
  // ═══ חלק 1 — פרטים אישיים ═══════════════════════════════════════════════
  {
    fieldNumber: '001',
    hebrewLabel: 'תעודת זהות הנישום',
    section: '1_identity',
    required: 'always',
    modelPath: 'identity.idNumber',
    sourceQuestionIds: ['identity_basics'],
    requiredDocuments: [
      { code: 'id_card', name: 'תעודת זהות + ספח', reason: 'אימות פרטי הנישום' },
    ],
  },
  {
    fieldNumber: '002',
    hebrewLabel: 'שם פרטי + שם משפחה',
    section: '1_identity',
    required: 'always',
    modelPath: 'identity.fullName',
    sourceQuestionIds: ['identity_basics'],
    requiredDocuments: [],
  },
  {
    fieldNumber: '003',
    hebrewLabel: 'תאריך לידה',
    section: '1_identity',
    required: 'always',
    modelPath: 'identity.dateOfBirth',
    sourceQuestionIds: ['identity_basics'],
    requiredDocuments: [],
  },
  {
    fieldNumber: '004',
    hebrewLabel: 'כתובת מגורים + עיר',
    section: '1_identity',
    required: 'always',
    modelPath: 'identity.address',
    sourceQuestionIds: ['identity_basics', 'qualifying_settlement'],
    requiredDocuments: [],
  },
  {
    fieldNumber: '113',
    hebrewLabel: 'מצב משפחתי',
    section: '1_identity',
    required: 'always',
    modelPath: 'identity.maritalStatus',
    sourceQuestionIds: ['marital_status'],
    requiredDocuments: [],
  },
  {
    fieldNumber: 'D-pct',
    hebrewLabel: 'אחוז נכות מוכרת',
    section: '1_identity',
    required: 'conditional',
    conditionalOn: (m) => m.identity?.hasDisability === true,
    modelPath: 'identity.disabilityBand',
    sourceQuestionIds: ['has_disability', 'disability_band'],
    requiredDocuments: [
      { code: 'disability_cert', name: 'אישור ועדה רפואית / ביטוח לאומי', reason: 'הוכחת אחוז הנכות לזיכוי מלא לפי סעיף 9(5)' },
    ],
    legalReference: 'סעיף 9(5) לפקודה',
  },

  // ═══ חלק 2 — בני בית ═════════════════════════════════════════════════════
  {
    fieldNumber: 'S-id',
    hebrewLabel: 'תעודת זהות בן/בת זוג',
    section: '2_family',
    required: 'conditional',
    conditionalOn: isMarried,
    modelPath: 'spouse.idNumber',
    sourceQuestionIds: ['marital_status', 'registered_spouse_role'],
    requiredDocuments: [
      { code: 'spouse_id', name: 'תעודת זהות בן/בת זוג', reason: 'נדרש לכל זוג נשוי' },
    ],
  },
  {
    fieldNumber: 'S-role',
    hebrewLabel: 'בן הזוג הרשום (מי משדר)',
    section: '2_family',
    required: 'conditional',
    conditionalOn: isMarried,
    modelPath: 'spouse.registeredRole',
    sourceQuestionIds: ['marital_status', 'registered_spouse_role'],
    requiredDocuments: [],
    legalReference: 'הוראות פקודה — בחירת בן זוג רשום',
  },
  {
    fieldNumber: 'S-calc',
    hebrewLabel: 'חישוב מאוחד או נפרד',
    section: '2_family',
    required: 'conditional',
    conditionalOn: (m) => isMarried(m) && m.identity?.spouseHasIncome === true,
    modelPath: 'spouse.eligibleSeparateCalc',
    sourceQuestionIds: ['marital_status', 'eligible_separate_calc'],
    requiredDocuments: [],
    legalReference: 'סעיף 66 לפקודה',
  },
  {
    fieldNumber: 'C-list',
    hebrewLabel: 'פירוט ילדים (שם, שנת לידה, החזקה)',
    section: '2_family',
    required: 'conditional',
    conditionalOn: (m) => (m.identity?.childrenCount ?? 0) > 0,
    modelPath: 'identity.children',
    sourceQuestionIds: ['children_count', 'children_details_required'],
    requiredDocuments: [
      { code: 'children_id', name: 'תעודות זהות ילדים + ספח', reason: 'אימות גילאי הילדים לחישוב נקודות זיכוי' },
    ],
  },
  {
    fieldNumber: 'C-special',
    hebrewLabel: 'ילד עם נכות / צרכים מיוחדים',
    section: '2_family',
    required: 'conditional',
    conditionalOn: (m) => m.identity?.childrenWithSpecialNeeds === true,
    modelPath: 'identity.childrenWithSpecialNeeds',
    sourceQuestionIds: ['children_count', 'children_special_needs'],
    requiredDocuments: [
      { code: 'special_child_cert', name: 'אישור נכות לילד', reason: 'נדרש לזיכוי לפי סעיף 40(ד)' },
    ],
    legalReference: 'סעיף 40(ד) לפקודה',
  },
  {
    // תוקן 2026-07: הקוד הרשמי לזיכוי משפחה חד-הורית הוא 026 (לא 029).
    fieldNumber: '026',
    hebrewLabel: 'זיכוי משפחה חד-הורית (הורה שילדיו בחזקתו)',
    section: '2_family',
    required: 'conditional',
    conditionalOn: (m) => m.identity?.isCustodialSingleParent === true,
    modelPath: 'identity.isCustodialSingleParent',
    sourceQuestionIds: ['marital_status', 'is_custodial_single_parent'],
    requiredDocuments: [
      { code: 'custody_decree', name: 'פסק דין למשמורת / אישור עיריה', reason: 'הוכחת הורה יחיד לזיכוי' },
    ],
    legalReference: 'סעיף 40(ב) לפקודה',
    dataLayer: 'question',
    codes: { registered: '026' },
    officialRef: 'מדריך 2025 עמ\' 31 — משפחה חד-הורית',
  },
  {
    // חדש: 029/129 הרשמיים = זיכוי כלכלת ילדים להורה פרוד שאינו משמורן.
    fieldNumber: '029',
    hebrewLabel: 'זיכוי כלכלת ילדים (הורה פרוד המשתתף בכלכלה)',
    section: '2_family',
    required: 'conditional',
    conditionalOn: (m) => m.identity?.paysChildEconomics === true,
    modelPath: 'identity.paysChildEconomics',
    sourceQuestionIds: ['child_economics'],
    requiredDocuments: [
      { code: 'child_support_proof', name: 'אסמכתאות השתתפות בכלכלת הילדים', reason: 'נקודת זיכוי (יחסית אם חלקית)' },
    ],
    legalReference: 'סעיף 40(ב)(1) לפקודה',
    dataLayer: 'question',
    codes: { registered: '029', spouse: '129' },
    officialRef: 'מדריך 2025 עמ\' 31 — כלכלת ילדים',
  },

  // ═══ חלק 3 — הכנסות מעבודה ═══════════════════════════════════════════════
  {
    fieldNumber: '158',
    hebrewLabel: 'הכנסה ברוטו ממשכורת',
    section: '3_income_salary',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'salary'),
    modelPath: 'income.salary.totalGross',
    sourceQuestionIds: ['salary_employer_count'],
    requiredDocuments: [
      { code: '106', name: 'טופס 106 מכל מעביד', reason: 'אישור שנתי על שכר ברוטו ומס שנוכה' },
    ],
    dataLayer: 'document',
    codes: { registered: '158', spouse: '172' },
    officialRef: 'מדריך 2025 עמ\' 12 — משכורת ושכר עבודה',
  },
  {
    fieldNumber: '042',
    hebrewLabel: 'מס שנוכה במקור משכר ומקצבאות',
    section: '3_income_salary',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'salary') || m.income?.hasPensionIncome === true,
    modelPath: 'income.salary.totalWithheld',
    sourceQuestionIds: ['salary_employer_count', 'had_withholding_at_source'],
    requiredDocuments: [
      { code: '106', name: 'טופס 106', reason: 'הסכום מופיע על גבי הטופס' },
    ],
    dataLayer: 'document',
    codes: { registered: '042', spouse: '044' },
    officialRef: 'מדריך 2025 עמ\' 37 — ניכוי במקור משכר/קצבאות',
  },
  {
    // תוקן 2026-07: 170 הרשמי = הכנסת עסק של בן הזוג. ספירת 106 היא נתון פנימי.
    fieldNumber: '106-count',
    hebrewLabel: 'מספר טפסי 106 שצורפו',
    section: '3_income_salary',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'salary'),
    modelPath: 'income.salaryEmployerCount',
    sourceQuestionIds: ['salary_employer_count'],
    requiredDocuments: [],
    dataLayer: 'auto',
    officialRef: 'נתון עזר פנימי — נגזר ממספר המעסיקים',
  },
  {
    // תוקן 2026-07: מענק פרישה חייב מדווח בשדות 258/272 (לא 037 שהוא תרומות).
    fieldNumber: '258-sev',
    hebrewLabel: 'מענק פרישה / פיצויי פיטורין חייבים',
    section: '3_income_salary',
    required: 'conditional',
    conditionalOn: (m) => m.income?.receivedSeverance === true,
    modelPath: 'income.severance.amount',
    sourceQuestionIds: ['received_severance'],
    requiredDocuments: [
      { code: '161', name: 'טופס 161 מהמעביד', reason: 'פירוט המענק — חלק חייב וחלק פטור' },
      { code: '134', name: 'אישור פקיד שומה לפריסה (אם בוצעה)', reason: 'פריסה למספר שנות מס' },
    ],
    legalReference: 'סעיף 9(7א) לפקודה',
    dataLayer: 'document',
    codes: { registered: '258', spouse: '272' },
    officialRef: 'מדריך 2025 עמ\' 12–13 — קצבאות ומענקי פרישה',
  },
  {
    fieldNumber: '009',
    hebrewLabel: 'יתרת שנות מס בפריסת פיצויים',
    section: '3_income_salary',
    required: 'conditional',
    conditionalOn: (m) => (m.income?.severanceSpreadYears ?? 0) > 0,
    modelPath: 'income.severanceSpreadYears',
    sourceQuestionIds: ['severance_spread'],
    requiredDocuments: [
      { code: 'spread_approval', name: 'אישור פקיד השומה לפריסה', reason: 'חובה לצרף את אישור הפריסה' },
    ],
    dataLayer: 'question',
    codes: { registered: '009' },
    officialRef: 'מדריך 2025 עמ\' 38 — פריסת פיצויי פיטורים',
  },
  {
    fieldNumber: '172',
    hebrewLabel: 'הכנסה ברוטו ממשכורת — בן/בת הזוג',
    section: '3_income_salary',
    required: 'conditional',
    conditionalOn: (m) => isMarried(m) && m.identity?.spouseHasIncome === true && m.spouse?.has106 === true,
    modelPath: 'spouse.salary.totalGross',
    sourceQuestionIds: ['marital_status', 'spouse_has_106'],
    requiredDocuments: [
      { code: '106_spouse', name: 'טופס 106 של בן/בת הזוג', reason: 'דיווח הכנסת התא המשפחתי' },
    ],
    dataLayer: 'document',
    codes: { spouse: '172' },
    officialRef: 'מדריך 2025 עמ\' 12',
  },
  {
    fieldNumber: '068',
    hebrewLabel: 'עבודה במשמרות בתעשייה (זיכוי 15%)',
    section: '3_income_salary',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasShiftWork === true,
    modelPath: 'income.hasShiftWork',
    sourceQuestionIds: ['shift_work'],
    requiredDocuments: [
      { code: '106_shift', name: 'טופס 106 עם פירוט תוספת משמרות', reason: 'הזיכוי מוגבל לתקרה שנתית' },
    ],
    dataLayer: 'document',
    codes: { registered: '068', spouse: '069' },
    officialRef: 'מדריך 2025 עמ\' 12, 34 — משמרות בתעשייה',
  },
  {
    fieldNumber: '282',
    hebrewLabel: 'הכנסה ממימוש אופציות 102 / 3i',
    section: '3_income_salary',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasOptions102 === true,
    modelPath: 'income.options102Total',
    sourceQuestionIds: ['has_options_102'],
    requiredDocuments: [
      { code: 'options_102_cert', name: 'אישור מהמעביד / נאמן על מימוש אופציות', reason: 'דיווח שווי המימוש' },
    ],
    legalReference: 'סעיף 102 / 3i לפקודה',
  },

  // ═══ חלק 4 — הכנסות מעסק ════════════════════════════════════════════════
  {
    fieldNumber: '150',
    hebrewLabel: 'הכנסה מעסק / משלח יד',
    section: '4_income_business',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'business'),
    modelPath: 'income.business.netIncome',
    sourceQuestionIds: ['business_kind', 'biz_revenue_band'],
    requiredDocuments: [
      { code: 'biz_pnl', name: 'דוח רווח-הפסד שנתי', reason: 'בסיס לחישוב הכנסה חייבת' },
      { code: 'annex_1320', name: 'נספח א\' (1320)', reason: 'פירוט ההכנסה מעסק לכל עסק בנפרד' },
    ],
    legalReference: 'סעיף 2(1) לפקודה',
    dataLayer: 'document',
    codes: { registered: '150', spouse: '170' },
    officialRef: 'מדריך 2025 עמ\' 11 — הכנסה מעסק/משלח יד',
  },
  {
    fieldNumber: '6111-req',
    hebrewLabel: 'חובת הגשת טופס 6111 (מחזור מעל 300K)',
    section: '4_income_business',
    required: 'conditional',
    conditionalOn: (m) => m.income?.bizRevenueBand === '300k_plus',
    modelPath: 'income.business.requires6111',
    sourceQuestionIds: ['biz_revenue_band'],
    requiredDocuments: [
      { code: '6111', name: 'טופס 6111 — מאזן ודוח רווח-הפסד מקודד', reason: 'חובה לעסק עם מחזור מעל 300,000 ₪ (הוראות 2025)' },
    ],
  },
  {
    fieldNumber: 'B-client-wh',
    hebrewLabel: 'ניכוי במקור מלקוחות (לעצמאי)',
    section: '4_income_business',
    required: 'conditional',
    conditionalOn: (m) => m.income?.bizHasClientWithholding === true,
    modelPath: 'income.business.clientWithholding',
    sourceQuestionIds: ['biz_has_client_withholding'],
    requiredDocuments: [
      { code: '857', name: 'טופס 857 — אישור ניכוי במקור', reason: 'סך הניכוי במקור מלקוחות לעצמאי' },
    ],
  },

  // ═══ חלק 5 — הכנסות פאסיביות ═════════════════════════════════════════════
  // תוקן 2026-07: שכ"ד למגורים בפטור מדווח כהכנסה פטורה (שדה 332 עד התקרה);
  // מסלול 10% ומס שולי מדווחים דרך אשף השכ"ד ונספח ב' (1321).
  {
    fieldNumber: '332',
    hebrewLabel: 'שכ"ד למגורים פטור (עד תקרת 5,654 ₪/חודש)',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'rental') && m.income?.rentalTrack === 'exempt',
    modelPath: 'income.rentalGrossAnnual',
    sourceQuestionIds: ['rental_track', 'rental_gross'],
    requiredDocuments: [
      { code: 'rental_contract', name: 'חוזה שכירות', reason: 'אימות שהשכ"ד בתקרת הפטור' },
    ],
    legalReference: 'חוק פטור ממס על דמי שכירות התש"ן-1990',
    dataLayer: 'question',
    codes: { joint: '332' },
    officialRef: 'מדריך 2025 עמ\' 14 — הכנסות פטורות משכ"ד למגורים',
  },
  {
    fieldNumber: 'R-flat10',
    hebrewLabel: 'הכנסה משכ"ד למגורים — מסלול 10% (סעיף 122)',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'rental') && m.income?.rentalTrack === 'flat10',
    modelPath: 'income.rentalGrossAnnual',
    sourceQuestionIds: ['rental_track', 'rental_gross'],
    requiredDocuments: [
      { code: 'rental_contract', name: 'חוזה שכירות', reason: 'אסמכתא להכנסה' },
      { code: 'rental_wh_cert', name: 'אישור ניכוי במקור משכ"ד (אם נוכה)', reason: 'קיזוז המס ששולם' },
    ],
    legalReference: 'סעיף 122 לפקודה',
    dataLayer: 'question',
    officialRef: 'מדריך 2025 עמ\' 14 — אשף שכ"ד במערכת השידור; אין קוד יחיד — מוזן באשף',
  },
  {
    fieldNumber: 'R-marginal',
    hebrewLabel: 'הכנסה משכ"ד — מס שולי (עם הוצאות, נספח ב\')',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'rental') && m.income?.rentalTrack === 'regular',
    modelPath: 'income.rentalGrossAnnual',
    sourceQuestionIds: ['rental_track', 'rental_gross'],
    requiredDocuments: [
      { code: 'rental_contract', name: 'חוזה שכירות', reason: 'אסמכתא להכנסה' },
      { code: 'rental_expenses', name: 'קבלות הוצאות (פחת, ריבית משכנתא, תיקונים)', reason: 'דרישה להוצאות במסלול שולי' },
      { code: 'annex_1321', name: 'נספח ב\' (1321)', reason: 'פירוט הכנסות והוצאות מנכס בית' },
    ],
    dataLayer: 'document',
    codes: { registered: '059', spouse: '201', joint: '301' },
    officialRef: 'מדריך 2025 עמ\' 14 — הכנסות מנכס בית דרך נספח ב\'',
    accountantAction: 'בניית נספח ב\' (1321) עם פחת והוצאות',
  },
  {
    fieldNumber: 'R-rent-paid',
    hebrewLabel: 'שכ"ד ששולם על דירת המגורים (ניכוי 122(ו) / שיקול מסלול)',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'rental') && m.income?.livesInRentedHome === true,
    modelPath: 'income.rentPaidAnnual',
    sourceQuestionIds: ['rents_own_home', 'rent_paid_annual'],
    requiredDocuments: [
      { code: 'own_rent_contract', name: 'חוזה השכירות של דירת המגורים + אסמכתאות תשלום', reason: 'ניכוי שכ"ד ששולם כנגד הכנסת השכירות (עד התקרה)' },
    ],
    legalReference: 'סעיף 122(ו) לפקודה',
    dataLayer: 'question',
    officialRef: 'תיקון 2023 — משכיר שגר בשכירות; מוזן במחשבון האופטימיזציה',
    accountantAction: 'הרצת מחשבון השכירות ובחירת מסלול (שאלת rental_track בשער הכיסוי)',
  },
  {
    fieldNumber: '120',
    hebrewLabel: 'השכרת נכס ששימש בעסק 10+ שנים (יגיעה אישית)',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasBusinessAssetRental10y === true,
    modelPath: 'income.hasBusinessAssetRental10y',
    sourceQuestionIds: ['business_asset_rental'],
    requiredDocuments: [
      { code: 'annex_1321', name: 'נספח ב\' (1321)', reason: 'דיווח ההשכרה' },
      { code: 'usage_proof', name: 'אסמכתא לשימוש עסקי 10+ שנים', reason: 'תנאי לסיווג כיגיעה אישית' },
    ],
    dataLayer: 'document',
    codes: { registered: '120', spouse: '220' },
    officialRef: 'מדריך 2025 עמ\' 13 — השכרת נכס ששימש בעסק',
  },
  // ריבית — הטופס מפצל לפי שיעור מס (10%/15%/20%/25%). הערכים נשלפים מ-867;
  // ללקוח יש שאלת טריגר אחת בלבד. הפיצול לשדות נעשה בשכבת המסמכים.
  {
    fieldNumber: '076',
    hebrewLabel: 'ריבית מפיקדונות ותוכניות חיסכון — 10%',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasInterestIncome === true,
    modelPath: 'income.interest.gross',
    sourceQuestionIds: ['has_interest_income'],
    requiredDocuments: [
      { code: '867', name: 'טופס 867 מכל בנק', reason: 'הפיצול לפי שיעור מס מופיע ב-867' },
    ],
    dataLayer: 'document',
    codes: { registered: '076', spouse: '216', joint: '316' },
    officialRef: 'מדריך 2025 עמ\' 38 — ריבית פיקדונות 10% (לא צמוד)',
  },
  {
    fieldNumber: '074',
    hebrewLabel: 'ריבית על ני"ע — 10%',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasInterestIncome === true,
    modelPath: 'income.interest.gross',
    sourceQuestionIds: ['has_interest_income'],
    requiredDocuments: [{ code: '867', name: 'טופס 867', reason: 'מקור הנתון' }],
    dataLayer: 'document',
    codes: { registered: '074', spouse: '208', joint: '308' },
    officialRef: 'מדריך 2025 עמ\' 38',
  },
  {
    fieldNumber: '060',
    hebrewLabel: 'ריבית ורווחים — 15% (כולל רווחי קופ"ג ודיבידנד מפעל מאושר)',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasInterestIncome === true,
    modelPath: 'income.interest.gross',
    sourceQuestionIds: ['has_interest_income'],
    requiredDocuments: [{ code: '867', name: 'טופס 867(ג)', reason: 'מקור הנתון' }],
    dataLayer: 'document',
    codes: { registered: '060', spouse: '211', joint: '311' },
    officialRef: 'מדריך 2025 עמ\' 15 — ריבית בשיעור 15%',
  },
  {
    fieldNumber: '067',
    hebrewLabel: 'ריבית — עד 20% (צמוד)',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasInterestIncome === true,
    modelPath: 'income.interest.gross',
    sourceQuestionIds: ['has_interest_income'],
    requiredDocuments: [{ code: '867', name: 'טופס 867(ג)', reason: 'מקור הנתון' }],
    dataLayer: 'document',
    codes: { registered: '067', spouse: '228', joint: '328' },
    officialRef: 'מדריך 2025 עמ\' 15 — ריבית בשיעור 20%',
  },
  {
    fieldNumber: '157',
    hebrewLabel: 'ריבית — עד 25% (משיכות קופ"ג 2012+)',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasInterestIncome === true,
    modelPath: 'income.interest.gross',
    sourceQuestionIds: ['has_interest_income'],
    requiredDocuments: [{ code: '867', name: 'טופס 867(ג)', reason: 'מקור הנתון' }],
    dataLayer: 'document',
    codes: { registered: '157', spouse: '257', joint: '357' },
    officialRef: 'מדריך 2025 עמ\' 16 — ריבית בשיעור 25%',
  },
  {
    fieldNumber: '043',
    hebrewLabel: 'ניכוי במקור מריבית',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasInterestIncome === true, // הניכוי נקרא מה-867
    modelPath: 'income.interest.withheld',
    sourceQuestionIds: ['has_interest_income'],
    requiredDocuments: [
      { code: '867', name: 'טופס 867 מהבנק', reason: 'הסכום מופיע ב-867' },
    ],
    dataLayer: 'document',
    codes: { joint: '043' },
    officialRef: 'מדריך 2025 — ניכוי במקור מריבית',
  },
  {
    // תוקן 2026-07: קצבאות חייבות מדווחות בשדות 258/272 (יחד עם מענקי פרישה).
    fieldNumber: '258-pension',
    hebrewLabel: 'קצבאות חייבות (פנסיה ממעביד/קרן, אובדן כושר)',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasPensionIncome === true,
    modelPath: 'income.pension.gross',
    sourceQuestionIds: ['has_pension_income'],
    requiredDocuments: [
      { code: '106_pension', name: 'טופס 106 מהגוף המשלם את הקצבה', reason: 'דיווח קצבאות שוטפות' },
    ],
    dataLayer: 'document',
    codes: { registered: '258', spouse: '272' },
    officialRef: 'מדריך 2025 עמ\' 12–13 — קצבאות ומענקי פרישה',
  },
  {
    fieldNumber: '101',
    hebrewLabel: 'קצבאות פטורות (משרד הביטחון, שאירים, נכות)',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasExemptPensions === true,
    modelPath: 'income.hasExemptPensions',
    sourceQuestionIds: ['exempt_pensions'],
    requiredDocuments: [
      { code: 'exempt_pension_cert', name: 'אישור על הקצבה הפטורה', reason: 'דיווח אינפורמטיבי — סעיפים 9א/9ב' },
    ],
    legalReference: 'סעיפים 9א, 9ב לפקודה',
    dataLayer: 'document',
    codes: { registered: '101', spouse: '102' },
    officialRef: 'מדריך 2025 עמ\' 23 — קצבאות פטורות',
  },
  {
    fieldNumber: '209',
    hebrewLabel: 'סה"כ הכנסות פטורות ובלתי חייבות',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) =>
      m.income?.hasExemptPensions === true ||
      (has(m, 'rental') && m.income?.rentalTrack === 'exempt'),
    modelPath: 'income.hasExemptPensions',
    sourceQuestionIds: ['exempt_pensions', 'rental_track'],
    requiredDocuments: [
      { code: 'exempt_income_detail', name: 'פירוט ההכנסות הפטורות', reason: 'חובה לצרף מסמך מתאר' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '209' },
    officialRef: 'מדריך 2025 עמ\' 23 — סה"כ הכנסות פטורות',
    accountantAction: 'ריכוז ההכנסות הפטורות ובדיקת השלכות (מס יסף, החזרים)',
  },
  // תוקן 2026-07: המבנה הרשמי (מדריך עמ' 11–12) — ההבחנה היא מעמד × בעלות,
  // לא סוג קצבה: 194/196 = תקבולים כשכיר (רשום/בן זוג), 250/270 = כעצמאי.
  {
    fieldNumber: 'NI-employee',
    hebrewLabel: 'תקבולי ביטוח לאומי חייבים — כשכיר (לידה, אבטלה, מילואים, פגיעה)',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) =>
      anyNiBenefit(m) && (has(m, 'salary') || !has(m, 'business')),
    modelPath: 'income.niBenefitsOwner',
    sourceQuestionIds: ['ni_maternity', 'ni_unemployment', 'ni_reserve_duty', 'ni_work_injury'],
    requiredDocuments: [
      { code: 'ni_annual_cert', name: 'אישור שנתי מביטוח לאומי על תקבולים חייבים', reason: 'סכום אחד שנתי לכל התקבולים כשכיר' },
    ],
    dataLayer: 'document',
    codes: { registered: '194', spouse: '196' },
    officialRef: 'מדריך 2025 עמ\' 12 — תקבולים כשכיר מהמוסד לביטוח לאומי',
  },
  {
    fieldNumber: 'NI-self',
    hebrewLabel: 'תקבולי ביטוח לאומי חייבים — כעצמאי (מילואים, לידה, פגיעה)',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => anyNiBenefit(m) && has(m, 'business'),
    modelPath: 'income.niBenefitsOwner',
    sourceQuestionIds: ['ni_maternity', 'ni_unemployment', 'ni_reserve_duty', 'ni_work_injury'],
    requiredDocuments: [
      { code: 'ni_annual_cert', name: 'אישור שנתי מביטוח לאומי על תקבולים חייבים', reason: 'סכום אחד שנתי לכל התקבולים כעצמאי' },
    ],
    dataLayer: 'document',
    codes: { registered: '250', spouse: '270' },
    officialRef: 'מדריך 2025 עמ\' 11 — תקבולים כעצמאי מהמוסד לביטוח לאומי',
  },
  {
    fieldNumber: '9-21',
    hebrewLabel: 'דמי מזונות שהתקבלו',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => (m.deductionsCredits?.alimonyReceivedAnnual ?? 0) > 0,
    modelPath: 'deductionsCredits.alimonyReceivedAnnual',
    sourceQuestionIds: ['alimony_received'],
    requiredDocuments: [
      { code: 'alimony_decree', name: 'פסק דין מזונות / הסכם', reason: 'דיווח תקבולי מזונות שחייבים חלקית' },
    ],
    legalReference: 'סעיף 9(21) לפקודה',
  },

  // ═══ חלק 6 — רווחי הון ודיבידנד ══════════════════════════════════════════
  {
    // תוקן 2026-07: אין שדה יחיד לרווחי ני"ע — הדיווח דרך נספח ג' (1322/1399),
    // והסיכומים זורמים לשדות 256/056. 142 הרשמי = דיבידנד (ראה DIV-regular).
    fieldNumber: 'CG-securities',
    hebrewLabel: 'רווחי הון מניירות ערך סחירים (נספח ג\')',
    section: '6_capital',
    required: 'conditional',
    conditionalOn: (m) => (m.income?.capitalSubTypes ?? []).includes('securities'),
    modelPath: 'income.capital.securitiesGain',
    sourceQuestionIds: ['capital_has_securities'],
    requiredDocuments: [
      { code: '867_capital', name: 'טופס 867 (א+ב) מכל בית השקעות/בנק', reason: 'אישור על רווחי הון ומס שנוכה' },
      { code: 'annex_1322', name: 'נספח ג\' (1322) / טופס 1399', reason: 'פירוט העסקאות לפי קודי עסקה' },
    ],
    dataLayer: 'document',
    codes: { joint: '256' },
    officialRef: 'מדריך 2025 עמ\' 50–56 — ני"ע סחירים; סיכומי מכירות לשדה 256',
    accountantAction: 'בניית נספח ג\' מכל טפסי ה-867; בדיקת קיזוזי הפסדים',
  },
  {
    fieldNumber: '054',
    hebrewLabel: 'מספר טופסי רווח הון / שבח שצורפו',
    section: '6_capital',
    required: 'conditional',
    conditionalOn: (m) => (m.income?.capitalSubTypes ?? []).length > 0,
    modelPath: 'income.capitalSubTypes',
    sourceQuestionIds: ['capital_has_securities', 'capital_has_crypto', 'capital_has_real_estate'],
    requiredDocuments: [],
    dataLayer: 'auto',
    codes: { joint: '054' },
    officialRef: 'מדריך 2025 עמ\' 14 — מספר טופסי רווח הון ושבח',
  },
  {
    fieldNumber: '253',
    hebrewLabel: 'ניכוי במקור מרווחי הון',
    section: '6_capital',
    required: 'conditional',
    conditionalOn: (m) => (m.income?.capitalSubTypes ?? []).includes('securities'), // הניכוי נקרא מה-867
    modelPath: 'income.capital.withheld',
    sourceQuestionIds: ['capital_has_securities'],
    requiredDocuments: [
      { code: '867_capital', name: 'טופס 867 (א+ב)', reason: 'הסכום מופיע ב-867' },
    ],
    dataLayer: 'document',
    codes: { joint: '253' },
    officialRef: 'מדריך 2025 עמ\' 37 — מתואם עם שדה 040',
  },
  {
    // תוקן 2026-07: 054 הרשמי = מספר טופסי רווח הון. שבח מקרקעין נקבע בשומת
    // מסמ"ק והקרן מדווחת בשדה 041 (ראה חלק 10).
    fieldNumber: 'CG-land',
    hebrewLabel: 'מכירת מקרקעין (שאינה דירת מגורים פטורה)',
    section: '6_capital',
    required: 'conditional',
    conditionalOn: (m) => (m.income?.capitalSubTypes ?? []).includes('real_estate'),
    modelPath: 'income.capital.realEstateGain',
    sourceQuestionIds: ['capital_has_real_estate'],
    requiredDocuments: [
      { code: 'land_appraisal', name: 'שומת מס שבח ממסמ"ק', reason: 'קרן המס עוברת לשדה 041' },
      { code: 'sale_contract', name: 'חוזה מכר', reason: 'אסמכתא לעסקה' },
    ],
    dataLayer: 'accountant',
    officialRef: 'מדריך 2025 עמ\' 36–37 — מס שבח בשומת מסמ"ק, שדה 041',
    accountantAction: 'בדיקת שומת השבח, שילוב בשדה 041 וקוד חריגה 114 במידת הצורך',
  },
  {
    fieldNumber: 'C-crypto',
    hebrewLabel: 'רווחי הון ממטבעות דיגיטליים',
    section: '6_capital',
    required: 'conditional',
    conditionalOn: (m) => (m.income?.capitalSubTypes ?? []).includes('crypto'),
    modelPath: 'income.capital.cryptoGain',
    sourceQuestionIds: ['capital_has_crypto'],
    requiredDocuments: [
      { code: 'crypto_history', name: 'דוח עסקאות מהבורסה (CSV/PDF)', reason: 'חישוב רווח/הפסד עסקה לעסקה' },
      { code: 'annex_1322', name: 'נספח ג\' עם קוד עסקה מאולצת 71', reason: 'דיווח קריפטו לפי הנחיות רשות המיסים' },
    ],
  },
  {
    // תוקן 2026-07: דיבידנד רגיל 25% = 141/241/341 (036 הרשמי הוא ביטוח חיים).
    fieldNumber: '141',
    hebrewLabel: 'דיבידנד — 25% (רגיל) / 30% (בעל מניות מהותי)',
    section: '6_capital',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'dividend'),
    modelPath: 'income.dividend.amount',
    sourceQuestionIds: ['dividend_controlling'],
    requiredDocuments: [
      { code: '867', name: 'טופס 867', reason: 'אישור על דיבידנד ומס שנוכה' },
    ],
    dataLayer: 'document',
    codes: { registered: '141', spouse: '241', joint: '341' },
    officialRef: 'מדריך 2025 עמ\' 15–16 — דיבידנד 25%; בעל מניות מהותי 30%',
  },
  {
    fieldNumber: '173',
    hebrewLabel: 'דיבידנד ממפעל מועדף / מאושר / מוטב — 20%',
    section: '6_capital',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasPreferredEnterpriseDividend === true,
    modelPath: 'income.hasPreferredEnterpriseDividend',
    sourceQuestionIds: ['dividend_preferred'],
    requiredDocuments: [
      { code: 'preferred_dividend_cert', name: 'אישור החברה על מקור הדיבידנד', reason: 'שיעור מס מופחת 20%' },
    ],
    legalReference: 'חוק עידוד השקעות הון',
    dataLayer: 'document',
    codes: { registered: '173', spouse: '275', joint: '375' },
    officialRef: 'מדריך 2025 עמ\' 15–16 — דיבידנד מפעל מועדף',
  },
  {
    fieldNumber: '427',
    hebrewLabel: 'הימורים, הגרלות ופרסים (35%, פטור עד 33,840 ₪)',
    section: '6_capital',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasGamblingOrPrizes === true,
    modelPath: 'income.hasGamblingOrPrizes',
    sourceQuestionIds: ['other_income_kinds'],
    requiredDocuments: [
      { code: 'prize_cert', name: 'אישור על הזכייה וניכוי המס', reason: 'מס 35% מעל תקרת הפטור' },
    ],
    legalReference: 'סעיף 2א לפקודה',
    dataLayer: 'document',
    codes: { joint: '427' },
    officialRef: 'מדריך 2025 עמ\' 47 — הימורים והגרלות',
  },

  // ═══ חלק 7 — הכנסות חו"ל ═══════════════════════════════════════════════
  {
    fieldNumber: 'F-tax-credit',
    hebrewLabel: 'זיכוי מס זר',
    section: '7_foreign',
    required: 'conditional',
    conditionalOn: (m) => m.income?.foreignPaidTaxAbroad === true,
    modelPath: 'income.foreign.taxCreditClaimed',
    sourceQuestionIds: ['foreign_paid_tax_abroad'],
    requiredDocuments: [
      { code: 'foreign_tax_cert', name: 'אישור על מס זר ששולם', reason: 'בסיס לזיכוי לפי אמנת מס' },
      { code: 'annex_1325', name: 'טופס 1325 — בקשה לזיכוי מס זר', reason: 'תביעת זיכוי' },
    ],
  },

  // ═══ חלק 8 — ניכויים וזיכויים ═════════════════════════════════════════════
  {
    fieldNumber: '037',
    hebrewLabel: 'תרומות לפי סעיף 46',
    section: '8_deductions',
    required: 'conditional',
    conditionalOn: (m) => (m.deductionsCredits?.donationAmount ?? 0) > 0,
    modelPath: 'deductionsCredits.donationAmount',
    sourceQuestionIds: ['donations'],
    requiredDocuments: [
      { code: 'donation_46', name: 'אישורי תרומה לפי סעיף 46 (או דיווח במערכת הדיגיטלית)', reason: 'מ-2024 תרומה שדווחה דיגיטלית פטורה מצירוף קבלות' },
    ],
    legalReference: 'סעיף 46 לפקודה',
    dataLayer: 'question',
    codes: { registered: '037', spouse: '237' },
    officialRef: 'מדריך 2025 עמ\' 34–35 — תרומות; מינ\' 207 ₪, זיכוי 35%',
  },
  {
    // תוקן 2026-07: ביטוח חיים = 036/081 (045 הרשמי הוא זיכוי עמית שכיר).
    fieldNumber: '036',
    hebrewLabel: 'דמי ביטוח חיים — לזיכוי 25%',
    section: '8_deductions',
    required: 'conditional',
    conditionalOn: (m) => (m.deductionsCredits?.lifeInsuranceAnnual ?? 0) > 0,
    modelPath: 'deductionsCredits.lifeInsuranceAnnual',
    sourceQuestionIds: ['life_insurance'],
    requiredDocuments: [
      { code: 'life_ins_cert', name: 'אישור ביטוח חיים (רכיב ריסק בלבד)', reason: 'הזיכוי על פרמיית הריסק, לא על רכיב חיסכון' },
    ],
    legalReference: 'סעיף 45א לפקודה',
    dataLayer: 'question',
    codes: { registered: '036', spouse: '081' },
    officialRef: 'מדריך 2025 עמ\' 33 — זיכוי ביטוח חיים',
  },
  {
    // תוקן 2026-07: הפקדה עצמאית לקצבה — ניכוי בשדות 135/180 (עמית עצמאי).
    fieldNumber: '135',
    hebrewLabel: 'תשלומים לקופ"ג לקצבה — "עמית עצמאי" (ניכוי)',
    section: '8_deductions',
    required: 'conditional',
    conditionalOn: (m) => (m.deductionsCredits?.selfPensionDeposits ?? 0) > 0,
    modelPath: 'deductionsCredits.selfPensionDeposits',
    sourceQuestionIds: ['self_pension'],
    requiredDocuments: [
      { code: 'pension_self_cert', name: 'אישור הפקדות שנתי מהקופה', reason: 'בסיס לניכוי לפי סעיף 47' },
    ],
    legalReference: 'סעיף 47 לפקודה',
    dataLayer: 'question',
    codes: { registered: '135', spouse: '180' },
    officialRef: 'מדריך 2025 עמ\' 28–29 — עמית עצמאי; תקרת עמית מוטב 24,069 ₪',
  },
  {
    fieldNumber: '268',
    hebrewLabel: 'תשלומים לקופ"ג לקצבה — זיכוי "עמית עצמאי" (35%)',
    section: '8_deductions',
    required: 'conditional',
    conditionalOn: (m) => (m.deductionsCredits?.selfPensionDeposits ?? 0) > 0,
    modelPath: 'deductionsCredits.selfPensionDeposits',
    sourceQuestionIds: ['self_pension'],
    requiredDocuments: [],
    legalReference: 'סעיף 45א לפקודה',
    dataLayer: 'auto',
    codes: { registered: '268', spouse: '269' },
    officialRef: 'מדריך 2025 עמ\' 33 — זיכוי קצבה עמית עצמאי; חלוקה אופטימלית בין ניכוי לזיכוי',
    accountantAction: 'אופטימיזציית פיצול ההפקדה בין ניכוי (135) לזיכוי (268)',
  },
  {
    fieldNumber: '136',
    hebrewLabel: 'קרן השתלמות לעצמאים (ניכוי עד 4.5%)',
    section: '8_deductions',
    required: 'conditional',
    conditionalOn: (m) => m.deductionsCredits?.hasKerenHashtalmutSelf === true,
    modelPath: 'deductionsCredits.kerenHashtalmutSelfAmount',
    sourceQuestionIds: ['biz_keren_hashtalmut'],
    requiredDocuments: [
      { code: 'keren_cert', name: 'אישור הפקדה שנתי מקרן ההשתלמות', reason: 'ניכוי עד 4.5% מההכנסה, תקרה 293,397 ₪' },
    ],
    legalReference: 'סעיף 17(5א) לפקודה',
    dataLayer: 'document',
    codes: { registered: '136', spouse: '137' },
    officialRef: 'מדריך 2025 עמ\' 28 — קרן השתלמות לעצמאים',
  },
  {
    fieldNumber: '25-alimony-paid',
    hebrewLabel: 'מזונות ששולמו (זיכוי)',
    section: '8_deductions',
    required: 'conditional',
    conditionalOn: (m) => (m.deductionsCredits?.alimonyPaidAnnual ?? 0) > 0,
    modelPath: 'deductionsCredits.alimonyPaidAnnual',
    sourceQuestionIds: ['alimony_paid'],
    requiredDocuments: [
      { code: 'alimony_decree_paid', name: 'פסק דין מזונות + אישורי תשלום', reason: 'זיכוי לפי סעיף 25 — בלבד אם מעוגן בפסק דין' },
    ],
    legalReference: 'סעיף 25 לפקודה',
  },
  {
    fieldNumber: 'S14',
    hebrewLabel: 'פטור לפי סעיף 14 (עולה חדש / תושב חוזר ותיק)',
    section: '8_deductions',
    required: 'conditional',
    conditionalOn: (m) => m.specialSituations?.electsSection14 === true,
    modelPath: 'specialSituations.electsSection14',
    sourceQuestionIds: ['elects_section_14'],
    requiredDocuments: [
      { code: 'aliyah_cert', name: 'תעודת עולה / אישור משרד הקליטה', reason: 'הוכחת זכאות לפטור 10 שנים' },
    ],
    legalReference: 'סעיף 14 לפקודה',
  },

  // ═══ חלק 9 — זיכויים נוספים ═════════════════════════════════════════════
  {
    fieldNumber: '024',
    hebrewLabel: 'זיכוי חייל/ת משוחרר/ת (תאריך שחרור + חודשי שירות)',
    section: '9_credits',
    required: 'conditional',
    conditionalOn: (m) => m.deductionsCredits?.isDischargedSoldier === true,
    modelPath: 'deductionsCredits.soldierServiceMonths',
    sourceQuestionIds: ['is_discharged_soldier', 'soldier_service_months'],
    requiredDocuments: [
      { code: 'discharge_cert', name: 'תעודת שחרור / אישור שירות', reason: 'הזיכוי נגזר ממשך השירות (מעל/מתחת 23 חודשים) ל-36 חודשים מהשחרור' },
    ],
    legalReference: 'סעיף 39א לפקודה',
    dataLayer: 'question',
    codes: { registered: '024', spouse: '124' },
    officialRef: 'מדריך 2025 עמ\' 32 — חייל משוחרר',
  },
  {
    fieldNumber: '181',
    hebrewLabel: 'זיכוי סיום תואר אקדמי / הוראה (קוד סוג 1–5)',
    section: '9_credits',
    required: 'conditional',
    conditionalOn: (m) => m.deductionsCredits?.hasAcademicDegree === true,
    modelPath: 'deductionsCredits.degreeTypeCode',
    sourceQuestionIds: ['has_academic_degree'],
    requiredDocuments: [
      { code: 'degree_cert', name: 'אישור זכאות לתואר + טופס 119', reason: 'קוד הסוג קובע את מספר הנקודות ומשכן' },
    ],
    legalReference: 'סעיפים 40ג–40ה לפקודה',
    dataLayer: 'question',
    codes: { registered: '181', spouse: '182' },
    officialRef: 'מדריך 2025 עמ\' 32–33 — סיום לימודים',
  },
  {
    fieldNumber: '045',
    hebrewLabel: 'זיכוי קצבה — "עמית שכיר" (מטופס 106)',
    section: '9_credits',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'salary'),
    modelPath: 'income.salary.pensionCredit',
    sourceQuestionIds: ['salary_employer_count'],
    requiredDocuments: [
      { code: '106', name: 'טופס 106', reason: 'הסכום מועתק משדה 045 בטופס 106' },
    ],
    legalReference: 'סעיף 45א לפקודה',
    dataLayer: 'document',
    codes: { registered: '045', spouse: '086' },
    officialRef: 'מדריך 2025 עמ\' 33 — זיכוי עמית שכיר',
  },
  {
    fieldNumber: '140',
    hebrewLabel: 'זיכוי ביטוח קצבת שאירים (35%)',
    section: '9_credits',
    required: 'conditional',
    conditionalOn: (m) => m.deductionsCredits?.hasSurvivorAnnuityInsurance === true,
    modelPath: 'deductionsCredits.hasSurvivorAnnuityInsurance',
    sourceQuestionIds: ['extra_deductions'],
    requiredDocuments: [
      { code: 'survivor_cert', name: 'אישור תשלומים לביטוח קצבת שאירים', reason: 'זיכוי 35% ללא תקרה' },
    ],
    dataLayer: 'question',
    codes: { registered: '140', spouse: '240' },
    officialRef: 'מדריך 2025 עמ\' 33 — קצבת שאירים',
  },
  {
    fieldNumber: '132',
    hebrewLabel: 'זיכוי החזקת בן משפחה במוסד (35% עד תקרה)',
    section: '9_credits',
    required: 'conditional',
    conditionalOn: (m) => m.deductionsCredits?.paysInstitutionCare === true,
    modelPath: 'deductionsCredits.paysInstitutionCare',
    sourceQuestionIds: ['extra_deductions'],
    requiredDocuments: [
      { code: 'institution_receipts', name: 'קבלות מקוריות מהמוסד', reason: 'זיכוי 35% מהחלק שמעל 12.5% מההכנסה' },
      { code: '127', name: 'טופס 127 — תעודה רפואית', reason: 'הוכחת מצב בן המשפחה' },
    ],
    legalReference: 'סעיף 44 לפקודה',
    dataLayer: 'question',
    codes: { registered: '132', spouse: '232' },
    officialRef: 'מדריך 2025 עמ\' 34 — החזקת בן משפחה במוסד; מגבלות הכנסה 301/188 אלף ₪',
    accountantAction: 'בדיקת חלופת זיכוי נכות (127) מול זיכוי מוסד — בוחרים אחד',
  },
  {
    fieldNumber: '046',
    hebrewLabel: 'תרומות למוסדות בארה"ב (עד 25% מהכנסת ארה"ב)',
    section: '9_credits',
    required: 'conditional',
    conditionalOn: (m) => m.deductionsCredits?.hasUsCharityDonations === true,
    modelPath: 'deductionsCredits.hasUsCharityDonations',
    sourceQuestionIds: ['extra_deductions'],
    requiredDocuments: [
      { code: 'us_donation_receipts', name: 'קבלות תרומה למוסדות אמריקאיים מוכרים', reason: 'לפי אמנת המס ישראל-ארה"ב' },
    ],
    dataLayer: 'question',
    codes: { registered: '046', spouse: '048' },
    officialRef: 'מדריך 2025 עמ\' 35 — תרומות ארה"ב',
  },
  {
    fieldNumber: '364',
    hebrewLabel: 'עודפי תרומות מ-3 שנים קודמות',
    section: '9_credits',
    required: 'conditional',
    conditionalOn: (m) => m.deductionsCredits?.hasDonationCarryover === true,
    modelPath: 'deductionsCredits.hasDonationCarryover',
    sourceQuestionIds: ['donations'],
    requiredDocuments: [],
    dataLayer: 'accountant',
    codes: { registered: '364', spouse: '292' },
    officialRef: 'מדריך 2025 עמ\' 35 — עודפי תרומות',
    accountantAction: 'איתור עודפים מדוחות קודמים והזנתם',
  },
  {
    fieldNumber: '139',
    hebrewLabel: 'זיכוי תושב אילת (10% עד תקרה)',
    section: '9_credits',
    required: 'conditional',
    conditionalOn: (m) => m.deductionsCredits?.isEilatResident === true,
    modelPath: 'deductionsCredits.isEilatResident',
    sourceQuestionIds: ['identity_basics'],
    requiredDocuments: [
      { code: 'eilat_residency', name: 'אישור תושבות אילת', reason: 'זיכוי 10% על יגיעה אישית שהופקה באילת, תקרה 259,800 ₪' },
    ],
    legalReference: 'חוק אזור סחר חופשי באילת',
    dataLayer: 'question',
    codes: { registered: '139', spouse: '183' },
    officialRef: 'מדריך 2025 עמ\' 35 — תושב אילת',
  },
  {
    fieldNumber: '287',
    hebrewLabel: 'זיכוי תושב יישוב מזכה',
    section: '9_credits',
    required: 'conditional',
    conditionalOn: (m) => m.identity?.livesInQualifyingSettlement === true,
    modelPath: 'identity.livesInQualifyingSettlement',
    sourceQuestionIds: ['identity_basics'],
    requiredDocuments: [
      { code: 'settlement_residency', name: 'תעודת תושב מהרשות המקומית', reason: 'נדרשים 12 חודשי תושבות רצופים' },
    ],
    dataLayer: 'question',
    codes: { registered: '287', spouse: '327' },
    officialRef: 'מדריך 2025 עמ\' 35–36 — יישובים מזכים (אשף); מעבר בין ישובים: 096/111',
  },
  {
    fieldNumber: '044',
    hebrewLabel: 'נקודות זיכוי עולה חדש / תושב חוזר',
    section: '9_credits',
    required: 'conditional',
    conditionalOn: (m) => m.identity?.residencyType === 'new_immigrant' || m.identity?.residencyType === 'returning_resident',
    modelPath: 'identity.residencyType',
    sourceQuestionIds: ['residency_type'],
    requiredDocuments: [
      { code: 'aliyah_cert', name: 'תעודת עולה + תאריך עלייה מדויק', reason: 'המדרגות מחושבות לפי חודשים מהעלייה' },
    ],
    legalReference: 'סעיף 35 לפקודה',
    dataLayer: 'auto',
    codes: { registered: '044', spouse: '088' },
    officialRef: 'מדריך 2025 עמ\' 32 — כללי נ"ז חדשים לעולים מ-1.1.2025 (54 חודשים)',
    accountantAction: 'חישוב מסלול נ"ז לפי תאריך עלייה (מסלול ישן/חדש)',
  },

  // ═══ חלק 10 — מיסים ששולמו במהלך השנה ════════════════════════════════════
  {
    fieldNumber: '040',
    hebrewLabel: 'מקדמות מ"ה ששולמו במהלך השנה',
    section: '10_tax_paid',
    required: 'conditional',
    conditionalOn: (m) => m.taxPaid?.paidAdvancePayments === true,
    modelPath: 'taxPaid.advancePaymentsTotal',
    sourceQuestionIds: ['paid_advance_payments'],
    requiredDocuments: [
      { code: 'advance_payments', name: 'דוח מקדמות שנתי מאזור האישי בשע"ם', reason: 'סכום המקדמות לקיזוז כנגד חוב המס' },
    ],
  },
  {
    fieldNumber: 'WH-summary',
    hebrewLabel: 'סך ניכוי במקור מכל המקורות',
    section: '10_tax_paid',
    required: 'conditional',
    conditionalOn: (m) => (m.taxPaid?.withholdingSources ?? []).length > 0,
    modelPath: 'taxPaid.withholdingTotal',
    sourceQuestionIds: ['had_withholding_at_source'],
    requiredDocuments: [
      { code: '857_837_summary', name: 'אישורי ניכוי במקור (857/837/867)', reason: 'סכום כולל לקיזוז' },
    ],
  },

  // ═══ חלק 11 — נסיבות מיוחדות ═════════════════════════════════════════════
  {
    fieldNumber: '64a-fam-co',
    hebrewLabel: 'חבר בחברה משפחתית (סעיף 64א)',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => m.specialSituations?.isFamilyCompanyMember === true,
    modelPath: 'specialSituations.isFamilyCompanyMember',
    sourceQuestionIds: ['is_family_company_member'],
    requiredDocuments: [
      { code: 'family_company_decl', name: 'אישור חבר בחברה משפחתית + טופס 2152', reason: 'ייחוס ההכנסה לבעל המניות' },
    ],
    legalReference: 'סעיף 64א לפקודה',
  },
  {
    fieldNumber: '75b-cfc',
    hebrewLabel: 'חברה זרה נשלטת (CFC)',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => m.specialSituations?.isForeignControllingShareholder === true,
    modelPath: 'specialSituations.isForeignControllingShareholder',
    sourceQuestionIds: ['is_foreign_controlling_shareholder'],
    requiredDocuments: [
      { code: 'cfc_decl', name: 'דיווח על חברה זרה נשלטת + טופס 150', reason: 'דיווח רווחי CFC' },
    ],
    legalReference: 'סעיף 75ב לפקודה',
  },
  {
    fieldNumber: 'kibbutz',
    hebrewLabel: 'חבר קיבוץ / מושב שיתופי',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => m.specialSituations?.isKibbutzMember === true,
    modelPath: 'specialSituations.isKibbutzMember',
    sourceQuestionIds: ['is_kibbutz_member'],
    requiredDocuments: [
      { code: 'kibbutz_cert', name: 'אישור חברות קיבוץ + פירוט הכנסות', reason: 'חישוב מס שונה לחברי קיבוץ' },
    ],
    legalReference: 'סעיף 54-58 לפקודה',
  },
  // הפסדים — פירוט לפי סוג (מדריך 2025 עמ' 26–27). מחליף את L-losses הבודד.
  {
    fieldNumber: '079',
    hebrewLabel: 'יתרת הפסד מעסק/משלח יד מועבר',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => hasLoss(m, 'business_carry'),
    modelPath: 'losses.kinds',
    sourceQuestionIds: ['carried_losses'],
    requiredDocuments: [
      { code: '1344', name: 'טופס 1344 — הפסדים מועברים', reason: 'פירוט יתרת ההפסד' },
      { code: 'last_year_assessment', name: 'שומה אחרונה', reason: 'אימות היתרה' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '079' },
    officialRef: 'מדריך 2025 עמ\' 26 — הפסד מעסק מועבר',
    accountantAction: 'מילוי 1344 ואימות היתרה מול השומה',
  },
  {
    fieldNumber: '179',
    hebrewLabel: 'הפסד מנכס בית (קיזוז רק כנגד אותו בניין)',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => hasLoss(m, 'rental_property'),
    modelPath: 'losses.kinds',
    sourceQuestionIds: ['carried_losses'],
    requiredDocuments: [
      { code: 'annex_1321', name: 'נספח ב\' (1321)', reason: 'פירוט ההפסד מהנכס' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '179' },
    officialRef: 'מדריך 2025 עמ\' 26 — הפסד מנכס בית',
  },
  {
    fieldNumber: '166',
    hebrewLabel: 'הפסדי הון מועברים (יחס 1:1 לרווח, 1:3.5 לאינפלציוני)',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => hasLoss(m, 'capital_carry'),
    modelPath: 'losses.kinds',
    sourceQuestionIds: ['carried_losses'],
    requiredDocuments: [
      { code: '1344', name: 'טופס 1344', reason: 'פירוט ההפסד' },
      { code: '867_loss', name: 'טופס 867 (א+ב) עם ההפסדים', reason: 'אימות הפסדי ני"ע' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '166' },
    officialRef: 'מדריך 2025 עמ\' 26–27 — הפסדי הון מועברים',
  },
  {
    fieldNumber: '160',
    hebrewLabel: 'הפסדי ני"ע שנוצרו עד 31.12.2005',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => hasLoss(m, 'securities_pre2006'),
    modelPath: 'losses.kinds',
    sourceQuestionIds: ['carried_losses'],
    requiredDocuments: [
      { code: '1344', name: 'טופס 1344', reason: 'פירוט ההפסד ההיסטורי' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '160' },
    officialRef: 'מדריך 2025 עמ\' 27 — הפסדי ני"ע ישנים (כללי קיזוז שונים)',
  },
  {
    fieldNumber: '299',
    hebrewLabel: 'הפסדי חו"ל להעברה (מנספח ד\')',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => hasLoss(m, 'foreign_carry') || has(m, 'foreign'),
    modelPath: 'losses.kinds',
    sourceQuestionIds: ['carried_losses', 'foreign_income_kinds'],
    requiredDocuments: [
      { code: 'annex_d', name: 'נספח ד\' — פירוט הפסדי חו"ל (479/480/481/466)', reason: 'העברת יתרות לשנה הבאה' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '299' },
    officialRef: 'מדריך 2025 עמ\' 49 — יתרות הפסדים מחו"ל',
  },
  {
    fieldNumber: '319',
    hebrewLabel: 'הפסד הון מהשקעה מזכה בחברת מו"פ',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => hasLoss(m, 'rnd_investment'),
    modelPath: 'losses.kinds',
    sourceQuestionIds: ['carried_losses'],
    requiredDocuments: [
      { code: 'rnd_invest_cert', name: 'אישור ההשקעה בחברת המו"פ', reason: 'הטבה לפי חוק האנג\'לים — תקרה 5 מ\' ₪' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '319' },
    officialRef: 'מדריך 2025 עמ\' 25 — השקעה מזכה בחברת מו"פ',
  },
  {
    fieldNumber: 'W-decl',
    hebrewLabel: 'הצהרת הון (לפי דרישת פקיד שומה)',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => m.specialSituations?.wealthDeclarationRequired === true,
    modelPath: 'specialSituations.wealthDeclarationRequired',
    sourceQuestionIds: ['special_situations_select'],
    requiredDocuments: [
      { code: 'wealth_declaration', name: 'טופס הצהרת הון', reason: 'מילוי הצהרת הון לפי דרישה' },
    ],
  },

  // ═══ ניכויים נוספים (מדריך עמ' 27–29) ═══════════════════════════════════
  {
    fieldNumber: '112',
    hebrewLabel: 'ביטוח אובדן כושר עבודה (ניכוי עד 3.5%)',
    section: '8_deductions',
    required: 'conditional',
    conditionalOn: (m) => m.deductionsCredits?.hasDisabilityInsurance === true,
    modelPath: 'deductionsCredits.hasDisabilityInsurance',
    sourceQuestionIds: ['extra_deductions'],
    requiredDocuments: [
      { code: 'ak_insurance_cert', name: 'אישור מבטח על פרמיית אובדן כושר', reason: 'ניכוי עד 3.5% מההכנסה, תקרה 399,480 ₪' },
      { code: '134-ak', name: 'טופס 134 (לשכיר)', reason: 'חישוב הניכוי לשכיר — שדות 206/207' },
    ],
    dataLayer: 'question',
    codes: { registered: '112', spouse: '113' },
    officialRef: 'מדריך 2025 עמ\' 27 — אובדן כושר עבודה (שכיר: 206/207)',
  },
  {
    fieldNumber: '030',
    hebrewLabel: 'דמי ביטוח לאומי ששולמו כעצמאי (ניכוי 52%)',
    section: '8_deductions',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'business') || m.deductionsCredits?.paidNiSelfEmployed === true,
    modelPath: 'deductionsCredits.paidNiSelfEmployed',
    sourceQuestionIds: ['business_kind'],
    requiredDocuments: [
      { code: 'ni_payment_cert', name: 'אישור שנתי מב"ל על תשלומים כעצמאי', reason: 'רק תשלומים בפועל, ללא קנסות/הצמדה/מס בריאות' },
    ],
    dataLayer: 'document',
    codes: { registered: '030', spouse: '089' },
    officialRef: 'מדריך 2025 עמ\' 28 — דמי ב"ל עצמאי; שכיר לתקופת עצמאות: 130/189',
  },
  {
    fieldNumber: '244',
    hebrewLabel: 'הכנסה מבוטחת + הפקדות מעביד (מטופס 106)',
    section: '8_deductions',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'salary'),
    modelPath: 'income.salary.insuredIncome',
    sourceQuestionIds: ['salary_employer_count'],
    requiredDocuments: [
      { code: '106', name: 'טופס 106', reason: 'שדות 244/245 (הכנסה מבוטחת) ו-248/249 (הפקדות) מועתקים מה-106' },
    ],
    dataLayer: 'document',
    codes: { registered: '244', spouse: '245' },
    officialRef: 'מדריך 2025 עמ\' 29 — הכנסה מבוטחת; הפקדות: 248/249',
  },
  {
    fieldNumber: 'SI-invest',
    hebrewLabel: 'השקעות בנות ניכוי: מחקר מדעי / נפט / סרטים',
    section: '8_deductions',
    required: 'conditional',
    conditionalOn: (m) => (m.deductionsCredits?.specialInvestments ?? []).length > 0,
    modelPath: 'deductionsCredits.specialInvestments',
    sourceQuestionIds: ['extra_deductions'],
    requiredDocuments: [
      { code: 'invest_certs', name: 'אישורי ההשקעה (מדען ראשי / טופס 858 / אישור ועדה)', reason: 'מחקר: 005/006, נפט: 116/117, סרטים: 118/119' },
    ],
    dataLayer: 'accountant',
    officialRef: 'מדריך 2025 עמ\' 28–29 — מחקר (סעיף 20א), נפט (858), סרטים',
    accountantAction: 'חישוב תקרות הניכוי (40% מהכנסה חייבת למחקר) והזנה בשדות הנכונים',
  },

  // ═══ חברות בבעלות, שותפויות ומשיכות (מדריך עמ' 14, 25–26) ══════════════
  {
    fieldNumber: '367',
    hebrewLabel: 'הכנסה מחברה משפחתית (שאינה מיגיעה אישית)',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => m.specialSituations?.isFamilyCompanyMember === true,
    modelPath: 'specialSituations.isFamilyCompanyMember',
    sourceQuestionIds: ['is_family_company_member'],
    requiredDocuments: [
      { code: 'fam_co_reports', name: 'דוח החברה המשפחתית + טופס 081', reason: 'ייחוס ההכנסה לנישום המייצג; שכר מהחברה: שדות 018/019' },
    ],
    legalReference: 'סעיף 64א לפקודה',
    dataLayer: 'accountant',
    codes: { registered: '367', spouse: '204', joint: '304' },
    officialRef: 'מדריך 2025 עמ\' 14 — חברה משפחתית; מחזור החברה מתווסף ל-294',
  },
  {
    fieldNumber: '159',
    hebrewLabel: 'הכנסה מחברת בית (סעיף 64)',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => m.income?.isHouseCompanyMember === true,
    modelPath: 'income.isHouseCompanyMember',
    sourceQuestionIds: ['companies_situations'],
    requiredDocuments: [
      { code: 'house_co_246', name: 'דיווח חברת בית (טופס 246)', reason: 'ייחוס הכנסות החברה לבעלי המניות' },
    ],
    legalReference: 'סעיף 64 לפקודה',
    dataLayer: 'accountant',
    codes: { registered: '159', spouse: '202', joint: '302' },
    officialRef: 'מדריך 2025 עמ\' 14 — חברת בית',
  },
  {
    fieldNumber: '167',
    hebrewLabel: 'הכנסות אחרות שאינן מיגיעה אישית (ריט, השכרת ציוד, שותפות נפט)',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasOtherIncome === true,
    modelPath: 'income.otherIncomeKinds',
    sourceQuestionIds: ['has_other_income'],
    requiredDocuments: [
      { code: 'other_income_docs', name: 'אסמכתאות להכנסות האחרות', reason: 'מס 31% ללא מדרגות מופחתות' },
    ],
    dataLayer: 'document',
    codes: { registered: '167', spouse: '205', joint: '305' },
    officialRef: 'מדריך 2025 עמ\' 14 — הכנסות אחרות',
  },
  {
    fieldNumber: '061',
    hebrewLabel: 'מכירת פטנט / הכנסה לאחר פטירה (מס עד 40%)',
    section: '5_income_passive',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasPatentOrPostMortemIncome === true,
    modelPath: 'income.hasPatentOrPostMortemIncome',
    sourceQuestionIds: ['companies_situations'],
    requiredDocuments: [
      { code: 'patent_docs', name: 'הסכם מכירת הפטנט / אסמכתת ההכנסה', reason: 'מס מוגבל 40% — מכירה חד-פעמית שלא במסגרת עיסוק' },
    ],
    dataLayer: 'accountant',
    codes: { registered: '061', spouse: '214', joint: '314' },
    officialRef: 'מדריך 2025 עמ\' 15 — פטנט והכנסה לאחר פטירה',
  },
  {
    fieldNumber: '323',
    hebrewLabel: 'משיכת בעל מניות מחברה — סעיף 3(ט1)',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasOwnerWithdrawals === true,
    modelPath: 'income.hasOwnerWithdrawals',
    sourceQuestionIds: ['companies_situations'],
    requiredDocuments: [
      { code: '1350', name: 'טופס 1350', reason: 'סיווג המשיכה: דיבידנד (323) / שכר (343) / עסק (350)' },
    ],
    legalReference: 'סעיף 3(ט1) לפקודה',
    dataLayer: 'accountant',
    officialRef: 'מדריך 2025 עמ\' 25–26 — משיכות מעל 100,000 ₪ מצטבר',
    accountantAction: 'סיווג המשיכה ומילוי 1350; רישום מקביל בשדות ההכנסה המתאימים',
  },
  {
    fieldNumber: '351',
    hebrewLabel: 'הכנסה מועברת מחברת מעטים (סעיף 62א)',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => m.income?.hasCloseCompanyPassthrough === true,
    modelPath: 'income.hasCloseCompanyPassthrough',
    sourceQuestionIds: ['companies_situations'],
    requiredDocuments: [
      { code: 'co_62a_reports', name: 'דוחות החברה + ייחוס ההכנסה', reason: 'חברת ארנק — ההכנסה מיוחסת לבעל המניות המהותי' },
    ],
    legalReference: 'סעיף 62א לפקודה',
    dataLayer: 'accountant',
    codes: { joint: '351' },
    officialRef: 'מדריך 2025 עמ\' 26 — סעיף 62א; רישום מקביל ב-158/172 או 150/170',
  },
  {
    fieldNumber: '1504',
    hebrewLabel: 'שותפות — ייחוס חלק יחסי',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => m.income?.isPartnershipMember === true,
    modelPath: 'income.isPartnershipMember',
    sourceQuestionIds: ['partnership_member'],
    requiredDocuments: [
      { code: '1504', name: 'טופס 1504 — הצהרה על שותפות', reason: 'ייחוס חלק יחסי במחזור, מלאי ורווח גולמי' },
    ],
    dataLayer: 'accountant',
    officialRef: 'מדריך 2025 עמ\' 8 — שותפות',
    accountantAction: 'מילוי 1504 וייחוס החלק היחסי בשדות העסק',
  },

  // ═══ הצהרות הפתיחה של הדוח (מדריך עמ' 5–9) ═════════════════════════════
  {
    fieldNumber: 'D-trust',
    hebrewLabel: 'נאמנות — יוצר / נהנה (שדה 271 לחלוקות)',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => (m.openingDeclarations?.trustRole ?? 'none') !== 'none',
    modelPath: 'openingDeclarations.trustRole',
    sourceQuestionIds: ['trust_role'],
    requiredDocuments: [
      { code: 'trust_forms', name: 'טפסי נאמנות: 151/148 (יוצר) / 142 (נהנה)', reason: 'דיווח נאמנויות לפי פרק רביעי 2' },
    ],
    legalReference: 'סעיפים 75ג–75יח לפקודה',
    dataLayer: 'accountant',
    codes: { joint: '271' },
    officialRef: 'מדריך 2025 עמ\' 7 — נאמנויות; נהנה מעל גיל 25 עם נכסים 500K+ חייב דיווח',
    accountantAction: 'זיהוי סוג הנאמנות ומילוי הטפסים הנלווים',
  },
  {
    fieldNumber: 'D-abroad500k',
    hebrewLabel: 'העברת 500,000 ₪+ לחו"ל (חובת דיווח שנתיים)',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => m.openingDeclarations?.transferredAbroad500k === true,
    modelPath: 'openingDeclarations.transferredAbroad500k',
    sourceQuestionIds: ['transferred_abroad'],
    requiredDocuments: [
      { code: 'transfer_docs', name: 'אסמכתאות ההעברה', reason: 'חובת דיווח בשנת ההעברה ובשנה שאחריה' },
    ],
    dataLayer: 'accountant',
    officialRef: 'מדריך 2025 עמ\' 6 — העברות כספים לחו"ל',
  },
  {
    fieldNumber: 'D-foreign-assets',
    hebrewLabel: 'נכסי חו"ל בשווי מעל ~2,086,000 ₪',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => m.openingDeclarations?.hasForeignAssetsOverThreshold === true,
    modelPath: 'openingDeclarations.hasForeignAssetsOverThreshold',
    sourceQuestionIds: ['foreign_assets'],
    requiredDocuments: [
      { code: 'foreign_assets_list', name: 'רשימת נכסי חו"ל ושוויים', reason: 'כולל נכסי בן זוג וילדים עד 18; פטור לעולה/תושב חוזר 10 שנים' },
    ],
    dataLayer: 'accountant',
    officialRef: 'מדריך 2025 עמ\' 6 — נכסים בחו"ל',
  },
  {
    fieldNumber: 'D-sec-turnover',
    hebrewLabel: 'מחזור מכירות ני"ע מעל ~2,810,000 ₪',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => m.openingDeclarations?.securitiesTurnoverOverThreshold === true,
    modelPath: 'openingDeclarations.securitiesTurnoverOverThreshold',
    sourceQuestionIds: ['capital_has_securities'],
    requiredDocuments: [],
    dataLayer: 'auto',
    officialRef: 'מדריך 2025 עמ\' 6 — טריגר חובת הגשה; נגזר מסך המכירות ב-867',
  },
  {
    fieldNumber: 'D-related-party',
    hebrewLabel: 'עסקאות עם צדדים קשורים בחו"ל (טופס 1385)',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => m.openingDeclarations?.hasRelatedPartyForeignTransactions === true,
    modelPath: 'openingDeclarations.hasRelatedPartyForeignTransactions',
    sourceQuestionIds: ['special_situations_select'],
    requiredDocuments: [
      { code: '1385', name: 'טופס 1385 לכל עסקה', reason: 'הצהרת מחירי שוק לפי סעיף 85א' },
    ],
    legalReference: 'סעיף 85א לפקודה',
    dataLayer: 'accountant',
    officialRef: 'מדריך 2025 עמ\' 8 — מחירי העברה',
  },
  {
    fieldNumber: 'D-opinion',
    hebrewLabel: 'חוות דעת / עמדה חייבת בדיווח / תכנון מס',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => m.openingDeclarations?.hasReportableOpinionOrPosition === true,
    modelPath: 'openingDeclarations.hasReportableOpinionOrPosition',
    sourceQuestionIds: ['special_situations_select'],
    requiredDocuments: [
      { code: '1345_1213', name: 'טופס 1345 / 1213 לפי העניין', reason: 'דיווח לפי סעיפים 131ד–131ה' },
    ],
    dataLayer: 'accountant',
    officialRef: 'מדריך 2025 עמ\' 8–9 — חוות דעת ועמדות חייבות בדיווח',
  },
  {
    fieldNumber: 'D-non-resident',
    hebrewLabel: 'טענת אי-תושבות למרות חזקת ימי שהייה (1348)',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => m.openingDeclarations?.claimsNonResidencyDaysPresumption === true,
    modelPath: 'openingDeclarations.claimsNonResidencyDaysPresumption',
    sourceQuestionIds: ['residency_type'],
    requiredDocuments: [
      { code: '1348', name: 'טופס 1348 — הצהרת תושבות', reason: 'פירוט ימי שהייה וזיקות' },
    ],
    dataLayer: 'accountant',
    officialRef: 'מדריך 2025 עמ\' 6 — חזקת ימי שהייה',
  },
  {
    fieldNumber: '307',
    hebrewLabel: 'פעילות אינטרנט / אנרגיות מתחדשות (קוד 2/3/4)',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => (m.openingDeclarations?.specialActivityCodes ?? []).length > 0,
    modelPath: 'openingDeclarations.specialActivityCodes',
    sourceQuestionIds: ['special_situations_select'],
    requiredDocuments: [],
    dataLayer: 'question',
    codes: { joint: '307' },
    officialRef: 'מדריך 2025 עמ\' 9 — קודי פעילות בשדה 307',
  },
  {
    fieldNumber: 'D-construction',
    hebrewLabel: 'קבלן — דיווח סיום בנייה (702)',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => m.openingDeclarations?.hasConstructionCompletion === true,
    modelPath: 'openingDeclarations.hasConstructionCompletion',
    sourceQuestionIds: ['special_situations_select'],
    requiredDocuments: [
      { code: '702', name: 'טופס 702 — סיום בנייה', reason: 'דיווח פרויקט שהסתיים' },
    ],
    dataLayer: 'accountant',
    officialRef: 'מדריך 2025 עמ\' 9 — קבלנים',
  },
  {
    fieldNumber: 'D-maternity-spread',
    hebrewLabel: 'בקשה לפריסת דמי לידה לשנה הבאה',
    section: '11_special',
    required: 'conditional',
    conditionalOn: (m) => m.income?.requestsMaternitySpread === true,
    modelPath: 'income.requestsMaternitySpread',
    sourceQuestionIds: ['ni_maternity'],
    requiredDocuments: [],
    dataLayer: 'question',
    officialRef: 'מדריך 2025 עמ\' 9 — פריסת דמי לידה',
  },
  {
    fieldNumber: 'D-surtax',
    hebrewLabel: 'מס יסף — הכנסה חייבת מעל 721,560 ₪ (3%)',
    section: '11_special',
    required: 'conditional',
    conditionalOn: () => false, // נגזר אוטומטית בשלב עיבוד הנתונים — לא מהשאלון
    modelPath: 'taxYear',
    sourceQuestionIds: [],
    requiredDocuments: [],
    legalReference: 'סעיף 121ב לפקודה',
    dataLayer: 'auto',
    officialRef: 'מדריך 2025 עמ\' 6 — מס יסף; מחושב אוטומטית מסך ההכנסות',
  },

  // ═══ נספח ד' — הכנסות חו"ל (מדריך עמ' 40–49) ════════════════════════════
  // כל זוג = ‹הכנסה, מס זר ששולם›. עד 10 מדינות; תקרת זיכוי לפי "סלים".
  {
    fieldNumber: 'FD-business',
    hebrewLabel: 'חו"ל: עסק/משלח יד (450) + מס זר (401)',
    section: '7_foreign',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'foreign') && (m.income?.foreignIncomeKinds ?? []).includes('business'),
    modelPath: 'income.foreignIncomeKinds',
    sourceQuestionIds: ['foreign_income_kinds'],
    requiredDocuments: [
      { code: 'foreign_biz_docs', name: 'דוח מפורט + אישורי מס זר', reason: 'מיובא לשדות 150/170 בטופס הראשי' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '450/401' },
    officialRef: 'מדריך 2025 עמ\' 41 — הכנסות עסק מחו"ל',
  },
  {
    fieldNumber: 'FD-salary',
    hebrewLabel: 'חו"ל: משכורת (458) + מס זר (403)',
    section: '7_foreign',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'foreign') && (m.income?.foreignIncomeKinds ?? []).includes('salary'),
    modelPath: 'income.foreignIncomeKinds',
    sourceQuestionIds: ['foreign_income_kinds'],
    requiredDocuments: [
      { code: 'foreign_salary_docs', name: 'תלושים/אישור שכר + אישור מס זר', reason: 'כולל שווי הטבות; מיובא ל-158/172' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '458/403' },
    officialRef: 'מדריך 2025 עמ\' 41 — משכורת מחו"ל',
  },
  {
    fieldNumber: 'FD-pension',
    hebrewLabel: 'חו"ל: קצבאות (445/468) + מס זר (404/407); קצבה 9ג: 442/423',
    section: '7_foreign',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'foreign') && ((m.income?.foreignIncomeKinds ?? []).includes('pension') || (m.income?.foreignIncomeKinds ?? []).includes('annuity')),
    modelPath: 'income.foreignIncomeKinds',
    sourceQuestionIds: ['foreign_income_kinds'],
    requiredDocuments: [
      { code: 'foreign_pension_docs', name: 'אישורי קצבה + מס זר', reason: 'קצבת עבודה → 258/272; סעיף 9ג — מס מוגבל למס הזר' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '445/404' },
    officialRef: 'מדריך 2025 עמ\' 42, 46 — קצבאות מחו"ל',
  },
  {
    fieldNumber: 'FD-rental',
    hebrewLabel: 'חו"ל: שכ"ד מקרקעין (459) / מסלול 15% (482) + מס זר (405)',
    section: '7_foreign',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'foreign') && (m.income?.foreignIncomeKinds ?? []).includes('rental'),
    modelPath: 'income.foreignIncomeKinds',
    sourceQuestionIds: ['foreign_income_kinds'],
    requiredDocuments: [
      { code: 'foreign_rental_docs', name: 'חוזים + אישורי מס זר + פירוט הוצאות', reason: 'מסלול 15% (482): רק פחת, בלי זיכוי מס זר' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '459/405' },
    officialRef: 'מדריך 2025 עמ\' 43, 46 — שכ"ד חו"ל; חלופת 122א בשדה 482',
    accountantAction: 'השוואת מסלול רגיל מול 15% ובחירת הזול',
  },
  {
    fieldNumber: 'FD-interest',
    hebrewLabel: 'חו"ל: ריבית לפי שיעורים (467/460/451/457) + מס זר',
    section: '7_foreign',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'foreign') && (m.income?.foreignIncomeKinds ?? []).includes('interest'),
    modelPath: 'income.foreignIncomeKinds',
    sourceQuestionIds: ['foreign_income_kinds'],
    requiredDocuments: [
      { code: 'foreign_interest_docs', name: 'דפי חשבון / אישורי ריבית + מס זר', reason: 'פיצול לפי שיעור: רגיל 467, 15% 460, 20% 451, 25% 457' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '467/406' },
    officialRef: 'מדריך 2025 עמ\' 43–45 — ריבית מחו"ל לפי שיעורים',
  },
  {
    fieldNumber: 'FD-dividend',
    hebrewLabel: 'חו"ל: דיבידנד 25% (462) / מהותי 30% (455) + מס זר (431)',
    section: '7_foreign',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'foreign') && (m.income?.foreignIncomeKinds ?? []).includes('dividend'),
    modelPath: 'income.foreignIncomeKinds',
    sourceQuestionIds: ['foreign_income_kinds'],
    requiredDocuments: [
      { code: 'foreign_div_docs', name: 'אישורי דיבידנד + מס זר שנוכה', reason: 'מיובא ל-141/241/341' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '462/431' },
    officialRef: 'מדריך 2025 עמ\' 44–45 — דיבידנד מחו"ל',
  },
  {
    fieldNumber: 'FD-capital',
    hebrewLabel: 'חו"ל: רווח הון (438/439) + מס זר (420/422)',
    section: '7_foreign',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'foreign') && (m.income?.foreignIncomeKinds ?? []).includes('capital'),
    modelPath: 'income.foreignIncomeKinds',
    sourceQuestionIds: ['foreign_income_kinds'],
    requiredDocuments: [
      { code: 'foreign_cg_docs', name: 'אישורי עסקאות + מס זר', reason: 'ני"ע סחירים: 439 (1322 קוד 56); אחר: 438 (1399 קוד 15)' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '438/420' },
    officialRef: 'מדריך 2025 עמ\' 45–46 — רווח הון מחו"ל',
  },
  {
    fieldNumber: 'FD-gambling',
    hebrewLabel: 'חו"ל: הימורים/הגרלות (427) + מס זר (416)',
    section: '7_foreign',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'foreign') && (m.income?.foreignIncomeKinds ?? []).includes('gambling'),
    modelPath: 'income.foreignIncomeKinds',
    sourceQuestionIds: ['foreign_income_kinds'],
    requiredDocuments: [
      { code: 'foreign_prize_docs', name: 'אישורי זכייה + מס זר', reason: '35% מעל הפטור' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '427/416' },
    officialRef: 'מדריך 2025 עמ\' 45 — הגרלות מחו"ל',
  },
  {
    fieldNumber: '290',
    hebrewLabel: 'סה"כ הכנסות חו"ל (סיכום נספח ד\')',
    section: '7_foreign',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'foreign'),
    modelPath: 'income.foreignCountries',
    sourceQuestionIds: ['foreign_countries', 'foreign_income_kinds'],
    requiredDocuments: [
      { code: 'annex_d', name: 'נספח ד\' מלא — עד 10 מדינות', reason: 'הסיכום עובר לטופס הראשי; תקרת זיכוי לפי סלים' },
    ],
    dataLayer: 'accountant',
    codes: { joint: '290' },
    officialRef: 'מדריך 2025 עמ\' 40–41, 49 — נספח ד\'; מחזור עסקי חו"ל: 493',
    accountantAction: 'בניית נספח ד\' לפי מדינות; חישוב תקרות זיכוי ועודף זיכוי (5 שנים)',
  },
  {
    fieldNumber: 'F-CFC',
    hebrewLabel: 'חנ"ז — דיבידנד רעיוני (472–477)',
    section: '7_foreign',
    required: 'conditional',
    conditionalOn: (m) => m.specialSituations?.isForeignControllingShareholder === true,
    modelPath: 'specialSituations.isForeignControllingShareholder',
    sourceQuestionIds: ['is_foreign_controlling_shareholder'],
    requiredDocuments: [
      { code: 'cfc_reports', name: 'דוחות החברה הזרה + טופס 150', reason: 'ייחוס רווחים לא מחולקים לבעל השליטה' },
    ],
    legalReference: 'סעיף 75ב לפקודה',
    dataLayer: 'accountant',
    codes: { joint: '472' },
    officialRef: 'מדריך 2025 עמ\' 47–48 — חנ"ז; חמי"ז: 463–465 (23%)',
    accountantAction: 'חישוב הדיבידנד הרעיוני ומעקב יתרות (473/475/476)',
  },

  // ═══ מיסים, מחזור ושדות סיכום (מדריך עמ' 36–40) ═════════════════════════
  {
    fieldNumber: '294',
    hebrewLabel: 'סך המחזור מעסק/משלח יד ללא מע"מ (בסיס מקדמות)',
    section: '10_tax_paid',
    required: 'conditional',
    conditionalOn: (m) => has(m, 'business'),
    modelPath: 'income.business.turnover',
    sourceQuestionIds: ['biz_revenue_band'],
    requiredDocuments: [],
    dataLayer: 'document',
    codes: { joint: '294' },
    officialRef: 'מדריך 2025 עמ\' 36 — מחזור; כולל מחזור חברה משפחתית לנישום המייצג',
  },
  {
    fieldNumber: '041',
    hebrewLabel: 'מס שבח שנקבע בשומת מסמ"ק (קרן בלבד)',
    section: '10_tax_paid',
    required: 'conditional',
    conditionalOn: (m) =>
      (m.income?.capitalSubTypes ?? []).includes('real_estate') ||
      m.taxPaid?.hasLandAppreciationAssessment === true,
    modelPath: 'taxPaid.hasLandAppreciationAssessment',
    sourceQuestionIds: ['capital_has_real_estate'],
    requiredDocuments: [
      { code: 'shevach_assessment', name: 'שומת מס שבח', reason: 'קרן המס בלבד, ללא ריבית והצמדה' },
    ],
    dataLayer: 'document',
    codes: { joint: '041' },
    officialRef: 'מדריך 2025 עמ\' 37 — מס שבח; קודי חריגה בשדה 114',
  },
  {
    fieldNumber: '353',
    hebrewLabel: 'ריבית והפרשי הצמדה על החזרי מס',
    section: '10_tax_paid',
    required: 'conditional',
    conditionalOn: (m) => m.taxPaid?.hasTaxRefundInterest === true,
    modelPath: 'taxPaid.hasTaxRefundInterest',
    sourceQuestionIds: ['paid_advance_payments'],
    requiredDocuments: [],
    dataLayer: 'accountant',
    codes: { joint: '353' },
    officialRef: 'מדריך 2025 עמ\' 37',
  },
  {
    fieldNumber: '253-other',
    hebrewLabel: 'ניכוי במקור מהכנסות אחרות (רווחי הון, שכ"ד, ספקים)',
    section: '10_tax_paid',
    required: 'conditional',
    conditionalOn: (m) => (m.taxPaid?.withholdingSources ?? []).some((s) => s !== 'salary_106'),
    modelPath: 'taxPaid.withholdingTotal',
    sourceQuestionIds: ['had_withholding_at_source'],
    requiredDocuments: [
      { code: '857_837_867', name: 'אישורי ניכוי במקור (857/837/867)', reason: 'סכום כולל לקיזוז — מתואם עם שדה 040' },
    ],
    dataLayer: 'document',
    codes: { joint: '253' },
    officialRef: 'מדריך 2025 עמ\' 37 — ניכוי במקור מהכנסות אחרות',
  },

  // ═══ חלק 12 — חתימה ═════════════════════════════════════════════════════
  {
    fieldNumber: 'SIG',
    hebrewLabel: 'הצהרה וחתימה',
    section: '12_signature',
    required: 'always',
    modelPath: 'signature',
    sourceQuestionIds: ['final_declaration'],
    requiredDocuments: [],
  },
];

// ─── עזרים ─────────────────────────────────────────────────────────────────

// אינדקס לפי מזהה שדה — לשליפת קודים רשמיים ותוויות ב-UI.
export const fieldByNumber: Record<string, Form1301FieldDef> = Object.fromEntries(
  form1301Fields.map((f) => [f.fieldNumber, f]),
);

// אינדקס הפוך: questionId → fieldNumbers שהיא מזינה (מופק אוטומטית)
export function buildQuestionTargetIndex(): Record<string, string[]> {
  const idx: Record<string, string[]> = {};
  for (const f of form1301Fields) {
    for (const q of f.sourceQuestionIds) {
      if (!idx[q]) idx[q] = [];
      idx[q].push(f.fieldNumber);
    }
  }
  return idx;
}

export const SECTION_LABELS: Record<import('./types').SectionKey, string> = {
  '1_identity': 'פרטים אישיים',
  '2_family': 'בני בית',
  '3_income_salary': 'הכנסות מעבודה',
  '4_income_business': 'הכנסות מעסק',
  '5_income_passive': 'הכנסות פאסיביות',
  '6_capital': 'רווחי הון ודיבידנד',
  '7_foreign': 'הכנסות חו"ל',
  '8_deductions': 'ניכויים וזיכויים',
  '9_credits': 'זיכויים נוספים',
  '10_tax_paid': 'מיסים ששולמו',
  '11_special': 'נסיבות מיוחדות',
  '12_signature': 'חתימה',
};
